// Le mapping pays → référentiel/devise est appliqué côté base (handle_new_user) ;
// cette liste ne sert qu'à alimenter le formulaire d'inscription.
export const PAYS = [
  { code: 'SN', nom: 'Sénégal' },
  { code: 'CI', nom: 'Côte d\'Ivoire' },
  { code: 'ML', nom: 'Mali' },
  { code: 'BF', nom: 'Burkina Faso' },
  { code: 'NE', nom: 'Niger' },
  { code: 'TG', nom: 'Togo' },
  { code: 'BJ', nom: 'Bénin' },
  { code: 'GW', nom: 'Guinée-Bissau' },
  { code: 'MR', nom: 'Mauritanie' },
  { code: 'MA', nom: 'Maroc' },
  { code: 'GH', nom: 'Ghana' },
  { code: 'GN', nom: 'Guinée' },
  { code: 'NG', nom: 'Nigeria' },
  { code: 'GM', nom: 'Gambie' },
  // Autres pays ajoutés
  { code: 'DZ', nom: 'Algérie' },
  { code: 'AO', nom: 'Angola' },
  { code: 'BW', nom: 'Botswana' },
  { code: 'BI', nom: 'Burundi' },
  { code: 'CV', nom: 'Cap-Vert' },
  { code: 'KM', nom: 'Comores' },
  { code: 'CD', nom: 'RD Congo' },
  { code: 'DJ', nom: 'Djibouti' },
  { code: 'EG', nom: 'Égypte' },
  { code: 'ER', nom: 'Érythrée' },
  { code: 'SZ', nom: 'Eswatini' },
  { code: 'ET', nom: 'Éthiopie' },
  { code: 'KE', nom: 'Kenya' },
  { code: 'LS', nom: 'Lesotho' },
  { code: 'LR', nom: 'Liberia' },
  { code: 'LY', nom: 'Libye' },
  { code: 'MG', nom: 'Madagascar' },
  { code: 'MW', nom: 'Malawi' },
  { code: 'MU', nom: 'Maurice' },
  { code: 'MZ', nom: 'Mozambique' },
  { code: 'NA', nom: 'Namibie' },
  { code: 'RW', nom: 'Rwanda' },
  { code: 'ST', nom: 'Sao Tomé-et-Principe' },
  { code: 'SC', nom: 'Seychelles' },
  { code: 'SL', nom: 'Sierra Leone' },
  { code: 'SO', nom: 'Somalie' },
  { code: 'ZA', nom: 'Afrique du Sud' },
  { code: 'SS', nom: 'Soudan du Sud' },
  { code: 'SD', nom: 'Soudan' },
  { code: 'TZ', nom: 'Tanzanie' },
  { code: 'TN', nom: 'Tunisie' },
  { code: 'UG', nom: 'Ouganda' },
  { code: 'ZM', nom: 'Zambie' },
  { code: 'ZW', nom: 'Zimbabwe' },
  { code: 'SA', nom: 'Arabie saoudite' },
  { code: 'AE', nom: 'Émirats arabes unis' },
  { code: 'QA', nom: 'Qatar' },
  { code: 'KW', nom: 'Koweït' },
  { code: 'BH', nom: 'Bahreïn' },
  { code: 'OM', nom: 'Oman' },
  { code: 'YE', nom: 'Yémen' },
  { code: 'JO', nom: 'Jordanie' },
  { code: 'LB', nom: 'Liban' },
  { code: 'SY', nom: 'Syrie' },
  { code: 'IQ', nom: 'Irak' },
  { code: 'IN', nom: 'Inde' },
  { code: 'PK', nom: 'Pakistan' },
  { code: 'BD', nom: 'Bangladesh' },
  { code: 'LK', nom: 'Sri Lanka' },
  { code: 'NP', nom: 'Népal' },
  { code: 'BT', nom: 'Bhoutan' },
  { code: 'MV', nom: 'Maldives' },
  { code: 'AF', nom: 'Afghanistan' },

] as const

export const ROLES: Record<string, string> = {
  admin: 'Administrateur',
  comptable: 'Comptable',
  chef_departement: 'Chef de département',
  rh: 'Ressources humaines',
  direction: 'Direction',
  lecteur: 'Lecteur',
}
